<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-bold text-gray-800">Portal Klien</h2><p class="mt-1 text-sm text-gray-500">{{ $client->company_name ?: $client->user->name }} · pengelolaan subscription dan QR.</p></div><a href="{{ route('client.plans') }}" style="background-color:#15803d;color:#ffffff;" class="rounded-lg px-4 py-2 font-bold">Lihat Paket</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">QR diberikan</p><p class="mt-2 text-3xl font-bold">{{ number_format($unitCount) }}</p><a class="mt-2 inline-block text-sm font-semibold text-green-700" href="{{ route('client.units') }}">Lihat QR saya</a></article><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Subscription</p><p class="mt-2 text-xl font-bold">{{ $subscription?->plan?->name ?? 'Belum berlangganan' }}</p><p class="mt-1 text-sm text-gray-600">Status: {{ $subscriptionDisplayStatus ?? '—' }}</p><p class="mt-1 text-xs text-gray-500">Kuota unit: {{ number_format($unitCount) }} / {{ number_format($subscription?->unit_limit ?? 0) }}</p></article><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Masa aktif sampai</p><p class="mt-2 text-xl font-bold">{{ $subscription?->ends_at?->format('d M Y') ?? '—' }}</p></article><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Scan / akses QR</p><p class="mt-2 text-3xl font-bold">{{ number_format($scanCount) }}</p></article><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Klik Google Review</p><p class="mt-2 text-3xl font-bold">{{ number_format($reviewClickCount) }}</p></article></div>
        <p class="-mt-3 text-xs text-gray-500">Aktivitas menghitung akses URL dan redirect, bukan orang unik atau jumlah review yang diposting.</p>
        @if(session('success'))<div class="rounded-lg bg-green-50 p-4 text-sm text-green-800">{{ session('success') }}</div>@endif
        @if(!$subscription)<section class="rounded-xl border border-green-200 bg-green-50 p-6"><h3 class="text-lg font-bold text-gray-900">Mulai dengan paket QR Review</h3><p class="mt-1 text-sm text-gray-600">Pilih paket yang sesuai untuk menerima unit QR dan memantau performanya.</p><a href="{{ route('client.plans') }}" style="background-color:#15803d;color:#ffffff;" class="mt-4 inline-flex rounded-lg px-5 py-3 font-bold">Pilih Paket</a></section>@endif
        <section class="overflow-hidden rounded-xl bg-white shadow-sm"><div class="border-b p-5"><h3 class="font-bold">Invoice terbaru</h3></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Invoice</th><th class="px-5 py-3">Jumlah</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Jatuh tempo</th><th></th></tr></thead><tbody class="divide-y">@forelse($invoices as $invoice)<tr><td class="px-5 py-3 font-mono">{{ $invoice->invoice_number }}</td><td class="px-5 py-3">Rp {{ number_format($invoice->amount, 0, ',', '.') }}</td><td class="px-5 py-3">{{ $invoice->status }}</td><td class="px-5 py-3">{{ $invoice->due_at?->format('d M Y') ?? '—' }}</td><td class="px-5 py-3 text-right"><a class="font-semibold text-green-700" href="{{ route('client.invoices.show', $invoice) }}">Detail</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-8 text-center text-gray-500">Belum ada invoice.</td></tr>@endforelse</tbody></table></div></section>
    </div></div>
</x-app-layout>
