<x-app-layout>
    <x-slot name="header"><div><h2 class="text-2xl font-bold text-gray-800">Paket Subscription</h2><p class="mt-1 text-sm text-gray-500">Pilih kuota QR dan periode yang sesuai dengan kebutuhan usaha Anda.</p></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-6xl space-y-5 px-4 sm:px-6 lg:px-8">
        @if(session('error'))<div class="rounded-lg bg-red-50 p-4 text-sm text-red-800">{{ session('error') }}</div>@endif
        @if(session('success'))<div class="rounded-lg bg-green-50 p-4 text-sm text-green-800">{{ session('success') }}</div>@endif
        @if(config('services.qr_billing.instructions'))<div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><strong>Informasi pembayaran:</strong><br>{{ config('services.qr_billing.instructions') }}</div>@endif
        <div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3">@forelse($plans as $plan)<article class="flex flex-col rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div><span class="rounded-full bg-green-50 px-3 py-1 text-xs font-bold text-green-800">{{ $plan->billing_cycle === 'yearly' ? 'TAHUNAN' : 'BULANAN' }}</span><h3 class="mt-4 text-xl font-bold text-gray-900">{{ $plan->name }}</h3><p class="mt-2 min-h-12 text-sm text-gray-500">{{ $plan->description }}</p></div><p class="mt-5 text-3xl font-extrabold text-gray-900">Rp {{ number_format($plan->price, 0, ',', '.') }}<span class="text-sm font-medium text-gray-500"> / {{ $plan->billing_cycle === 'yearly' ? 'tahun' : 'bulan' }}</span></p><p class="mt-2 text-sm text-gray-600">Maksimal {{ number_format($plan->unit_limit) }} unit QR</p><form method="POST" action="{{ route('client.subscribe', $plan) }}" class="mt-auto pt-6">@csrf<button @disabled($hasOpenSubscription) style="background-color:{{ $hasOpenSubscription ? '#9ca3af' : '#15803d' }};color:#ffffff;" class="w-full rounded-lg px-5 py-3 font-bold disabled:cursor-not-allowed">{{ $hasOpenSubscription ? 'Selesaikan subscription aktif' : 'Pilih paket' }}</button></form></article>@empty<div class="col-span-full rounded-xl bg-white p-10 text-center text-gray-500">Belum ada paket aktif. Silakan hubungi admin.</div>@endforelse</div>
    </div></div>
</x-app-layout>
