<x-app-layout>
    <x-slot name="header"><div><h2 class="text-2xl font-bold text-gray-800">Analytics Dynamic QR</h2><p class="mt-1 text-sm text-gray-500">Ringkasan unit dan aktivasi destination menurut template.</p></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @php($activityMax = max(1, collect($dailyActivity)->max(fn ($day) => max($day['scans'], $day['reviews']))))
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Total scan / akses QR</p><p class="mt-2 text-3xl font-bold">{{ number_format($scanTotal) }}</p></article><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Klik menuju Google Review</p><p class="mt-2 text-3xl font-bold">{{ number_format($reviewClickTotal) }}</p></article><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Destination aktif</p><p class="mt-2 text-3xl font-bold">{{ number_format($destinationCount) }}</p></article><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Pendapatan terverifikasi</p><p class="mt-2 text-2xl font-bold">Rp {{ number_format($paidRevenue, 0, ',', '.') }}</p></article><article class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Invoice menunggu</p><p class="mt-2 text-3xl font-bold">{{ number_format($pendingInvoices) }}</p></article></div>
        <section class="rounded-xl bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-bold text-gray-800">Tren aktivitas 14 hari</h3><p class="mt-1 text-sm text-gray-500">Perbandingan scan QR dengan klik menuju halaman review.</p></div><div class="flex gap-4 text-xs font-semibold"><span class="flex items-center gap-2"><i class="h-3 w-3 rounded-sm bg-green-600"></i>Scan</span><span class="flex items-center gap-2"><i class="h-3 w-3 rounded-sm bg-blue-600"></i>Klik review</span></div></div><div class="mt-6 overflow-x-auto"><div class="flex h-48 min-w-[700px] items-end gap-2 border-b border-gray-200 px-2">@foreach($dailyActivity as $day)<div class="flex h-full min-w-8 flex-1 flex-col items-center justify-end"><div class="flex h-[160px] w-full items-end justify-center gap-1"><div title="{{ $day['scans'] }} scan" class="w-2/5 rounded-t bg-green-600" style="height:{{ max(2, (int) round($day['scans'] / $activityMax * 100)) }}%"></div><div title="{{ $day['reviews'] }} klik review" class="w-2/5 rounded-t bg-blue-600" style="height:{{ max(2, (int) round($day['reviews'] / $activityMax * 100)) }}%"></div></div><span class="mt-2 text-[10px] text-gray-500">{{ $day['label'] }}</span></div>@endforeach</div></div><p class="mt-3 text-xs text-gray-500">Hitungan scan adalah jumlah akses URL, bukan jumlah orang unik. Klik review adalah redirect ke Google, bukan jumlah review yang diposting.</p></section>
        @php($templateActivityMax = max(1, (int) $templates->max(fn ($template) => max($template->scan_events, $template->review_click_events))))
        <section class="rounded-xl bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-bold text-gray-800">Aktivitas per template</h3><p class="mt-1 text-sm text-gray-500">Perbandingan total akses QR dan redirect review.</p></div><div class="flex gap-4 text-xs font-semibold"><span class="flex items-center gap-2"><i class="h-3 w-3 rounded-sm bg-green-600"></i>Scan</span><span class="flex items-center gap-2"><i class="h-3 w-3 rounded-sm bg-blue-600"></i>Klik review</span></div></div>
            <div class="mt-5 space-y-5">@forelse($templates as $template)<div><div class="mb-2 flex justify-between gap-3 text-sm"><span class="font-semibold text-gray-700">{{ $template->name }}</span><span class="whitespace-nowrap text-gray-500">{{ number_format($template->scan_events) }} scan · {{ number_format($template->review_click_events) }} klik</span></div><div class="space-y-1.5"><div class="h-2.5 overflow-hidden rounded-full bg-gray-100"><div class="h-full rounded-full bg-green-600" style="width:{{ round($template->scan_events / $templateActivityMax * 100) }}%"></div></div><div class="h-2.5 overflow-hidden rounded-full bg-gray-100"><div class="h-full rounded-full bg-blue-600" style="width:{{ round($template->review_click_events / $templateActivityMax * 100) }}%"></div></div></div></div>@empty<p class="text-sm text-gray-500">Belum ada template.</p>@endforelse</div>
        </section>
        <section class="overflow-hidden rounded-xl bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-5 py-4">Template</th><th class="px-5 py-4">Total</th><th class="px-5 py-4">Kosong</th><th class="px-5 py-4">Diproses</th><th class="px-5 py-4">Aktif</th><th class="px-5 py-4">Nonaktif</th><th class="px-5 py-4">Aktivasi</th><th class="px-5 py-4">Scan</th><th class="px-5 py-4">Klik review</th></tr></thead><tbody class="divide-y divide-gray-100">
            @forelse($templates as $template)<tr><td class="px-5 py-4 font-semibold">{{ $template->name }}</td><td class="px-5 py-4">{{ number_format($template->total_units) }}</td><td class="px-5 py-4">{{ number_format($template->empty_units) }}</td><td class="px-5 py-4">{{ number_format($template->pending_units) }}</td><td class="px-5 py-4">{{ number_format($template->active_units) }}</td><td class="px-5 py-4">{{ number_format($template->disabled_units) }}</td><td class="px-5 py-4">{{ $template->total_units ? number_format($template->active_units / $template->total_units * 100, 1) : '0.0' }}%</td><td class="px-5 py-4">{{ number_format($template->scan_events) }}</td><td class="px-5 py-4">{{ number_format($template->review_click_events) }}</td></tr>@empty<tr><td colspan="9" class="px-5 py-8 text-center text-gray-500">Belum ada template untuk dianalisis.</td></tr>@endforelse
        </tbody></table></div></section>
    </div></div>
</x-app-layout>
